// Font Family Options
export const fonts = {
    'times-new-roman': {
        name: 'Times New Roman',
        family: '"Times New Roman", Times, serif',
        description: 'Classic serif font, ideal for academic and formal documents',
        category: 'serif',
    },
    'georgia': {
        name: 'Georgia',
        family: 'Georgia, serif',
        description: 'Elegant serif font with excellent readability',
        category: 'serif',
    },
    'arial': {
        name: 'Arial',
        family: 'Arial, Helvetica, sans-serif',
        description: 'Clean and modern sans-serif font',
        category: 'sans-serif',
    },
    'helvetica': {
        name: 'Helvetica',
        family: 'Helvetica, Arial, sans-serif',
        description: 'Professional sans-serif font',
        category: 'sans-serif',
    },
    'courier-new': {
        name: 'Courier New',
        family: '"Courier New", Courier, monospace',
        description: 'Monospace font for technical content',
        category: 'monospace',
    },
    'verdana': {
        name: 'Verdana',
        family: 'Verdana, Geneva, sans-serif',
        description: 'Highly legible sans-serif font',
        category: 'sans-serif',
    },
    'palatino': {
        name: 'Palatino',
        family: '"Palatino Linotype", "Book Antiqua", Palatino, serif',
        description: 'Elegant serif font with Renaissance origins',
        category: 'serif',
    },
    'garamond': {
        name: 'Garamond',
        family: 'Garamond, "Hoefler Text", "Times New Roman", serif',
        description: 'Classic old-style serif font',
        category: 'serif',
    },
    'trebuchet': {
        name: 'Trebuchet MS',
        family: '"Trebuchet MS", "Lucida Grande", sans-serif',
        description: 'Humanist sans-serif font',
        category: 'sans-serif',
    },
    'inter': {
        name: 'Inter',
        family: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        description: 'Modern sans-serif optimized for screens',
        googleFont: 'Inter:wght@300;400;500;600;700;800',
        category: 'sans-serif',
    },
    'roboto': {
        name: 'Roboto',
        family: '"Roboto", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        description: 'Google\'s signature sans-serif font',
        googleFont: 'Roboto:wght@300;400;500;700;900',
        category: 'sans-serif',
    },
    'open-sans': {
        name: 'Open Sans',
        family: '"Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        description: 'Friendly and neutral sans-serif',
        googleFont: 'Open+Sans:wght@300;400;600;700;800',
        category: 'sans-serif',
    },
    'lora': {
        name: 'Lora',
        family: '"Lora", Georgia, "Times New Roman", serif',
        description: 'Contemporary serif with calligraphic roots',
        googleFont: 'Lora:wght@400;500;600;700',
        category: 'serif',
    },
    'merriweather': {
        name: 'Merriweather',
        family: '"Merriweather", Georgia, serif',
        description: 'Designed for pleasant reading on screens',
        googleFont: 'Merriweather:wght@300;400;700;900',
        category: 'serif',
    },
    'source-sans-pro': {
        name: 'Source Sans Pro',
        family: '"Source Sans Pro", -apple-system, BlinkMacSystemFont, sans-serif',
        description: 'Adobe\'s sans-serif, excellent for small print',
        googleFont: 'Source+Sans+Pro:wght@300;400;600;700',
        category: 'sans-serif',
    },
    'noto-sans': {
        name: 'Noto Sans',
        family: '"Noto Sans", Arial, sans-serif',
        description: 'Google\'s universal font, highly legible at small sizes',
        googleFont: 'Noto+Sans:wght@300;400;500;600;700',
        category: 'sans-serif',
    },
    'fira-sans': {
        name: 'Fira Sans',
        family: '"Fira Sans", -apple-system, BlinkMacSystemFont, sans-serif',
        description: 'Designed for Firefox OS, great clarity at small sizes',
        googleFont: 'Fira+Sans:wght@300;400;500;600;700',
        category: 'sans-serif',
    },
    'pt-sans': {
        name: 'PT Sans',
        family: '"PT Sans", Arial, sans-serif',
        description: 'Optimized for Cyrillic, excellent small print legibility',
        googleFont: 'PT+Sans:wght@400;700',
        category: 'sans-serif',
    },
    'cabin': {
        name: 'Cabin',
        family: '"Cabin", Arial, sans-serif',
        description: 'Humanist sans-serif, compact and clear for dense layouts',
        googleFont: 'Cabin:wght@400;500;600;700',
        category: 'sans-serif',
    },
    'nunito-sans': {
        name: 'Nunito Sans',
        family: '"Nunito Sans", -apple-system, BlinkMacSystemFont, sans-serif',
        description: 'Rounded sans-serif, friendly and readable at small sizes',
        googleFont: 'Nunito+Sans:wght@300;400;600;700;800',
        category: 'sans-serif',
    },
    // Monospace Fonts
    'fira-code': {
        name: 'Fira Code',
        family: '"Fira Code", "Courier New", monospace',
        description: 'Modern monospace with programming ligatures',
        googleFont: 'Fira+Code:wght@300;400;500;600;700',
        category: 'monospace',
    },
    'jetbrains-mono': {
        name: 'JetBrains Mono',
        family: '"JetBrains Mono", "Courier New", monospace',
        description: 'Developer-focused monospace font',
        googleFont: 'JetBrains+Mono:wght@300;400;500;600;700',
        category: 'monospace',
    },
    // Display Fonts
    'playfair-display': {
        name: 'Playfair Display',
        family: '"Playfair Display", Georgia, serif',
        description: 'High-contrast serif for headlines and titles',
        googleFont: 'Playfair+Display:wght@400;500;600;700;800;900',
        category: 'display',
    },
    'cinzel': {
        name: 'Cinzel',
        family: '"Cinzel", Georgia, serif',
        description: 'Classical Roman-inspired serif font',
        googleFont: 'Cinzel:wght@400;500;600;700;800;900',
        category: 'display',
    },
    // Modern Sans-Serif
    'raleway': {
        name: 'Raleway',
        family: '"Raleway", -apple-system, BlinkMacSystemFont, sans-serif',
        description: 'Elegant thin sans-serif with geometric style',
        googleFont: 'Raleway:wght@300;400;500;600;700;800',
        category: 'sans-serif',
    },
    'montserrat': {
        name: 'Montserrat',
        family: '"Montserrat", -apple-system, BlinkMacSystemFont, sans-serif',
        description: 'Urban geometric sans-serif inspired by Buenos Aires',
        googleFont: 'Montserrat:wght@300;400;500;600;700;800;900',
        category: 'sans-serif',
    },
    'poppins': {
        name: 'Poppins',
        family: '"Poppins", -apple-system, BlinkMacSystemFont, sans-serif',
        description: 'Geometric sans-serif with Indian Devanagari support',
        googleFont: 'Poppins:wght@300;400;500;600;700;800;900',
        category: 'sans-serif',
    },
    // ✍️ HANDWRITING FONTS
    'caveat': {
        name: '✍️ Caveat — Student Notes',
        family: '"Caveat", cursive',
        description: 'Casual, fast-written student handwriting. Slightly uneven, authentic note-taking feel.',
        googleFont: 'Caveat:wght@400;500;600;700',
        category: 'handwriting',
        handwritingStyle: 'student',
    },
    'kalam': {
        name: '✍️ Kalam — Neat Student',
        family: '"Kalam", cursive',
        description: 'Clean, neat handwriting style. Looks like a top student\'s careful notes.',
        googleFont: 'Kalam:wght@300;400;700',
        category: 'handwriting',
        handwritingStyle: 'student-neat',
    },
    'patrick-hand': {
        name: '✍️ Patrick Hand — Printed Notes',
        family: '"Patrick Hand", cursive',
        description: 'Clear printed handwriting, like notes written in block letters by an engineer.',
        googleFont: 'Patrick+Hand',
        category: 'handwriting',
        handwritingStyle: 'engineer',
    },
    'indie-flower': {
        name: '✍️ Indie Flower — Bubbly Notes',
        family: '"Indie Flower", cursive',
        description: 'Bubbly, rounded handwriting. Fun and casual student style.',
        googleFont: 'Indie+Flower',
        category: 'handwriting',
        handwritingStyle: 'student-fun',
    },
    'architects-daughter': {
        name: '✍️ Architect — Technical Print',
        family: '"Architects Daughter", cursive',
        description: 'Technical printed handwriting. Looks like an architect or engineer\'s blueprint notes.',
        googleFont: 'Architects+Daughter',
        category: 'handwriting',
        handwritingStyle: 'engineer',
    },
    'just-another-hand': {
        name: '✍️ Just Another Hand — Quick Scrawl',
        family: '"Just Another Hand", cursive',
        description: 'Fast, slightly messy handwriting. Great for rushed lecture notes.',
        googleFont: 'Just+Another+Hand',
        category: 'handwriting',
        handwritingStyle: 'rushed',
    },
    'gloria-hallelujah': {
        name: '✍️ Gloria Hallelujah — Comic Notes',
        family: '"Gloria Hallelujah", cursive',
        description: 'Comic book inspired handwriting. Expressive, large, and bold.',
        googleFont: 'Gloria+Hallelujah',
        category: 'handwriting',
        handwritingStyle: 'expressive',
    },
    'handlee': {
        name: '✍️ Handlee — Casual Scribble',
        family: '"Handlee", cursive',
        description: 'Natural, slightly tilted casual handwriting for everyday notes.',
        googleFont: 'Handlee',
        category: 'handwriting',
        handwritingStyle: 'casual',
    },
    'permanent-marker': {
        name: '✍️ Permanent Marker — Bold Marker',
        family: '"Permanent Marker", cursive',
        description: 'Bold thick marker writing. Great for headings and emphasis.',
        googleFont: 'Permanent+Marker',
        category: 'handwriting',
        handwritingStyle: 'marker',
    },
    'reenie-beanie': {
        name: '✍️ Reenie Beanie — Tiny Scrawl',
        family: '"Reenie Beanie", cursive',
        description: 'Small, tight handwriting. Perfect for cramming lots of info — like a real cheatsheet.',
        googleFont: 'Reenie+Beanie',
        category: 'handwriting',
        handwritingStyle: 'cramped',
    },
    'dancing-script': {
        name: '✍️ Dancing Script — Elegant Cursive',
        family: '"Dancing Script", cursive',
        description: 'Flowing elegant cursive, like careful cursive handwriting practice.',
        googleFont: 'Dancing+Script:wght@400;500;600;700',
        category: 'handwriting',
        handwritingStyle: 'cursive',
    },
    'shadows-into-light': {
        name: '✍️ Shadows Into Light — Pen Strokes',
        family: '"Shadows Into Light", cursive',
        description: 'Light ballpoint pen style handwriting. Thin, clean strokes.',
        googleFont: 'Shadows+Into+Light',
        category: 'handwriting',
        handwritingStyle: 'pen',
    },
    'pacifico': {
        name: 'Pacifico',
        family: '"Pacifico", cursive',
        description: 'Retro surf-style script font',
        googleFont: 'Pacifico',
        category: 'display',
    },
};

// Group fonts by category for the UI selector
export const fontCategories = {
    'Sans-Serif': ['inter', 'roboto', 'open-sans', 'noto-sans', 'fira-sans', 'pt-sans', 'cabin', 'nunito-sans', 'arial', 'helvetica', 'verdana', 'trebuchet', 'source-sans-pro', 'raleway', 'montserrat', 'poppins'],
    'Serif': ['times-new-roman', 'georgia', 'palatino', 'garamond', 'lora', 'merriweather'],
    'Monospace': ['courier-new', 'fira-code', 'jetbrains-mono'],
    'Display': ['playfair-display', 'cinzel', 'pacifico'],
    '✍️ Handwriting': ['caveat', 'kalam', 'patrick-hand', 'indie-flower', 'architects-daughter', 'just-another-hand', 'gloria-hallelujah', 'handlee', 'permanent-marker', 'reenie-beanie', 'dancing-script', 'shadows-into-light'],
};

export default fonts;
